import "../globals.css";

import type { Metadata } from "next";
import Providers from "@/app/_shared/components/Providers";
import { inter, larsseit } from "@/lib/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${inter.variable} ${larsseit.variable} ${inter.className}`}>
          {children}
        </body>
      </Providers>
    </html>
  );
}
